# Generated by Django 4.2.7 on 2023-11-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, verbose_name='Скилл')),
                ('procent', models.CharField(max_length=100, verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Скилы',
                'verbose_name_plural': 'Скилл',
            },
        ),
    ]
