# Generated by Django 4.2.7 on 2023-12-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(max_length=100, verbose_name='Годы работы')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('company', models.CharField(max_length=100, verbose_name='коспания где работал')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыты работы',
            },
        ),
    ]
