# Generated by Django 4.2.7 on 2023-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='comment',
            field=models.TextField(default=1, verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.CharField(max_length=100, verbose_name='компания где работал'),
        ),
    ]
