# Generated by Django 4.2.7 on 2023-12-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_work_comment_alter_work_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.CharField(max_length=100, verbose_name='comment'),
        ),
    ]
