# Generated by Django 4.2.7 on 2023-12-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_work_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100, verbose_name='Год окончаеия')),
                ('education', models.CharField(max_length=255, verbose_name='Научный стенпень')),
                ('h_e_i', models.CharField(max_length=100, verbose_name='ВУЗ')),
                ('comment', models.TextField(max_length=100, verbose_name='Комментарии')),
            ],
        ),
    ]
