# Generated by Django 4.2.7 on 2023-12-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образовании'},
        ),
    ]
